language: python
python: 
    - "3.3"
    - "3.4"
env:
    - TOX_ENV=testenv
install:
    - "pip install coverage"
    - "pip install nose"
script:
    - "nosetests --with-coverage --cover-package=pelecanus"
