language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
env:
    - TOX_ENV=testenv
install:
    - "pip install -e ."
    - "pip install coveralls"
script:
    - "py.test test"
after_success:
  - coveralls
